new error
Lispy2.0 > (+ 2 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 257, in evalLoop
  File "<string>", line 60, in meval
  File "<string>", line 176, in eval_name
  File "<string>", line 153, in lookup_variables
TypeError: 'in <string>' requires string as left operand, not dict